Row
-----------------------------------------------------------------------
### Demographic Parity 
```{r}
# data visuals

## demographic parity
graph <- demo_sum %>%
  filter(uds_test) %>%
  arrange(race_group,age_group, delivery_month)

g <- ggplot(graph, aes(x=delivery_month, y=perc_total, color=race_group)) +
  geom_line() +
  geom_vline(linetype="dashed", color="darkgreen", xintercept = as.numeric(qi_date)) + 
  geom_point(aes(size = total, alpha = 0.5, text=paste('Percent of monthers tested:', label_percent()(perc_total),
                 '<br>Total number of births:', total)), show.legend = FALSE) + 
  # annotate("text", x = qi_date-months(1), y = 0.5, label = '2028-03-01\nQI Intervention', size = 3, angle = 90) +
  guides(color=guide_legend(title="Race")) +
  facet_grid(.~age_group)

ggplotly(g, tooltip = c('text')) 
```

Row
-----------------------------------------------------------------------

### Group Difference P-values from 2-Way ANOVA

```{r}
intervention_date <- '2028-03-01'
anova_results_post <- aov(y ~ race_group + age_group, data=tab_data %>% filter(delivery_date >= intervention_date))
anova_results_pre <- aov(y ~ race_group + age_group, data=tab_data %>% filter(delivery_date < intervention_date))
anova_results_post <- summary(anova_results_post)[[1]] %>% select(`Pr(>F)`) %>%
  rownames_to_column() %>% rename(`Post-Intervention P-Value` = `Pr(>F)`)
anova_results_pre <- summary(anova_results_pre)[[1]] %>% select(`Pr(>F)`) %>%
  rownames_to_column() %>% rename(`Pre-Intervention P-Value` = `Pr(>F)`)
anova_results_pre %>%
  inner_join(anova_results_post, by='rowname') %>%
  datatable()
```

Row
-----------------------------------------------------------------------

### Logistic regression model - Pre Intvervention
```{r}
anova_results_pre <- glm(uds_test ~ race_group + age_group, data=data %>% filter(pre_post_QI=="Pre"), family = "binomial") %>% tbl_regression(add_estimate_to_reference_rows=TRUE)
anova_results_pre
```
### Logistic regression model - Post Intvervention
```{r}
anova_results_post <- glm(uds_test ~ race_group + age_group, data=data %>% filter(pre_post_QI=="Post"), family = "binomial") %>% tbl_regression(add_estimate_to_reference_rows=TRUE)
anova_results_post
```
